<form action = "cons_alunos_ra.php" method="POST">
        <fieldset>
            <legend>Informe o RA</legend>
                <p>
                <label for="ra">Digite o RA:</label>
                <input type="number" name="ra" id="ra" min="1" step="1">
                </p>
            <input type="submit" value="Enviar"/>
            <input type="reset" value="Limpar"/>
        </fieldset>
    </form>